#!/usr/bin/env sh

# Shell script to patch WPS Office Theme
# Author: owl4ce
# License: GPL-3.0
# --------------------------------
# https://github.com/owl4ce/wpsotp

# WPS Office Suite filename
WRITER="wps"
PRESENTATION="wpp"
SPREADSHEET="et"
PDF="wpspdf"

LC_ALL=C LANG=C R="\033[1;31m" G="\033[1;32m" M="\033[1;35m" W="\033[1;37m" NC="\033[0m"

# Functions
# - Output messages
err() { printf "${R} > error: ${NC}$*\n"; exit 1; }
msg() { printf "${G} > ${NC}$*\n"; }
msg_patch() { printf "${G} > ${M}$1 ${NC}$2 ${R}(error)\n"; }
msg_patching() { printf "${G} > ${NC}$1 ${M}$2 ${NC}$3"; }
msg_patching_ok() { printf "${G} OK${NC}\n"; }
msg_patching_fail() { printf "${R} FAIL${NC}\n"; }
# - Check dependencies
checkdep() { type "$1" >/dev/null || err "${M}$1${NC} is not installed. Please install it first!"; }
# - Check GTK Theme
checkgtk() {
    # GTK-2.0 rc file locations
    HOME_THEME_DIR="$HOME/.themes/$GTK_THEME_TARGET/gtk-2.0/gtkrc"
    GLOBAL_THEME_DIR="/usr/share/themes/$GTK_THEME_TARGET/gtk-2.0/gtkrc"
    if [ -f "$HOME_THEME_DIR" ]; then
        GTK_THEME="$HOME_THEME_DIR"
    elif [ -f "$GLOBAL_THEME_DIR" ]; then
        GTK_THEME="$GLOBAL_THEME_DIR"
    else
        err "${M}$GTK_THEME_TARGET${NC} GTK Theme is not exists!"
    fi
}

# Privilege detection
if type "sudo" >/dev/null; then
    PRIV="sudo"
elif type "doas" >/dev/null; then
    PRIV="doas"
else
    err "There is no ${M}sudo${NC} or ${M}doas${NC} installed."
fi

# Checks dependencies
checkdep "$WRITER"
checkdep "$PRESENTATION"
checkdep "$SPREADSHEET"
checkdep "$PDF"
checkdep "sed"

unpatch() {
    if grep -E "\-style=gtk+|GTK2_RC_FILES" "$(type "$*")" >/dev/null; then
        $PRIV echo "" >/dev/null ; msg_patching "Unpatching" "$*" ".."
        $PRIV sed -i 's\"-style=gtk+"\""\' "$(type "$*")" && \
        [ "$*" = "$PDF" ] && $PRIV sed -i '/gOpt=".*"/d' "$(type "$*")" || : && \
        $PRIV sed -i '/GTK2_RC_FILES/d' "$(type "$*")" && \
        [ "$*" = "$PDF" ] && $PRIV sed -i 's\${gApp} ${gOpt} "\${gApp} "\' "$(type "$*")" || : && \
        msg_patching_ok || msg_patching_fail
    else
        msg_patch "$*" "theme not patched!" ; !
    fi
}

patch() {
    if ! grep -E "\-style=gtk+|GTK2_RC_FILES" "$(type "$*")" >/dev/null; then
        $PRIV echo "" >/dev/null ; msg_patching "Patching" "$*" ".."
        $PRIV sed -i 's\gOpt=""\gOpt="-style=gtk+"\' "$(type "$*")" && \
        [ "$*" = "$PDF" ] && $PRIV sed -i '/gBinPath=$(dirname "$0")/i gOpt="-style=gtk+"' "$(type "$*")" || : && \
        $PRIV sed -i "/gOpt=\"-style=gtk+\"/a export GTK2_RC_FILES=$GTK_THEME" "$(type "$*")" && \
        [ "$*" = "$PDF" ] && $PRIV sed -i 's\${gApp} "\${gApp} ${gOpt} "\' "$(type "$*")" || : && \
        msg_patching_ok || msg_patching_fail
    else
        msg_patch "$*" "theme already patched!" ; !
    fi
}

case $1 in
    -u) unpatch "$WRITER"
        unpatch "$PRESENTATION"
        unpatch "$SPREADSHEET"
        unpatch "$PDF"
    ;;
    -*) err "unknown option ($1)"
    ;;
    *)  msg "Enter GTK Theme to be applied!"
        printf " ${M}[${NC} Light Theme ${M}]\n ${M}: $*${NC}"
        read GTK_THEME_TARGET ; checkgtk
        msg_patching "Using" "$GTK_THEME_TARGET" "GTK Theme ..\n"
        patch "$WRITER"
        patch "$PRESENTATION"
        patch "$SPREADSHEET"
        patch "$PDF"
    ;;
esac
